pipeline {
    agents {
      label 'master'
    }
    stages {
      stage ('Gathering') {
        steps {
          sh 'echo Gathering facts about deployment'
        }
      }
      stage ('Deploy') {
        steps {
          retry(3) {
            sh 'echo Retrying script'
          }
          timeout(time: 3, unit: MINUTES) {
            sh 'echo Running Health Check'
          }
        }
      }
    }
}